### ISSUE TITLE
Testing page is broken

### ISSUE THREAD

**Issue by the-frey** [InterWasm/docs#344]
Currently, https://docs.cosmwasm.com/docs/1.0/smart-contracts/testing errors out, only seems to happen on Chrome.

<img width="979" alt="Screenshot 2022-04-22 at 14 30 17" src="https://user-images.githubusercontent.com/2385077/164724181-0de1b7a9-d77b-4ea7-8002-48637b2057f7.png">

**Comment by 0xMalaz** [comment]
The issue appears to be solved by the 'beta-18' update provided by the docusaurus team. Feel free to open another issue if a similar problem arises.
