### ISSUE TITLE
Error in documentation : Set up CLI

### ISSUE THREAD

**Issue by alpereira7** [InterWasm/docs#352]
There is an error in documentation, to set up CLI:
https://docs.cosmwasm.com/docs/1.0/getting-started/setting-env/

`# add wallets for testing
wasmd keys add wallet
>
{
  "name": "wallet",
  "type": "local",
  "address": "wasm1pze5wsf0dg0fa4ysnttugn0m22ssf3t4a9yz3h",
  "pubkey": "{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A09EWZLG2oI9mNLG9SbTHjMJEZvH+DGhshjLsUKP5Ijd"}",
  "mnemonic": "hobby bunker rotate piano satoshi planet network verify else market spring toward pledge turkey tip slim word jaguar congress thumb flag project chalk inspire"
}

wasmd keys add wallet2`

returns 

    ~$ >
    bash: syntax error near unexpected token `newline'

**Comment by 0xMalaz** [comment]
That is the output you are supposed to see, not what you type if I'm not mistaken but I see the reason behind your confusion. We'll try to make it clearer.

To add a wallet just write and save the mnemonic if neccessary.

```console
wasmd keys add wallet
```

To add a wallet with a mnemonic type
```console
wasmd keys add wallet --recover
```
followed by the mnemonic.

**Comment by webmaster128** [comment]
If you look at the rendered page, I think it is really unclear what is the input and what is the output of the console. What is the `>`? Also, the JSON output is broken for some reason.

<img width="623" alt="Bildschirmfoto 2022-05-04 um 23 46 14" src="https://user-images.githubusercontent.com/2603011/166831067-1da3ad84-3429-4047-9a93-ef94b32297ea.png">
